// <auto-generated />
using System;
using APFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724084158_SeedWorkflowTransitions")]
    partial class SeedWorkflowTransitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APFlow.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresDualControl")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("ApprovalPolicies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Domain = "InvoiceApproval",
                            IsDeleted = false,
                            RequiredRole = "FINANCE_MANAGER",
                            RequiresDualControl = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("DuplicateCheckReason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPotentialDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceDocumentBlobName")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SourceDocumentContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEmailMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierInvoiceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenantId", "InvoiceDate");

                    b.HasIndex("TenantId", "SourceDocumentContentHash");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "SupplierId");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.InvoiceNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TenantId", "InvoiceId");

                    b.ToTable("InvoiceNotes", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.StatusReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "Code")
                        .IsUnique();

                    b.ToTable("StatusReferences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "RECEIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Received",
                            SortOrder = 10,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Code = "EXTRACTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Extracted",
                            SortOrder = 15,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Code = "PROCESSING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Processing",
                            SortOrder = 20,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Code = "DUPLICATE_SUSPECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Duplicate Suspected",
                            SortOrder = 30,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Code = "AWAITING_REVIEW",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Review",
                            SortOrder = 40,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Code = "NEEDS_QUERY",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Needs Query",
                            SortOrder = 50,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Code = "QUERY_RAISED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Query Raised",
                            SortOrder = 60,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Code = "AWAITING_SUPPLIER_RESPONSE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Supplier Response",
                            SortOrder = 70,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Code = "APPROVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Approved",
                            SortOrder = 80,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000a"),
                            Code = "REJECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Rejected",
                            SortOrder = 90,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000b"),
                            Code = "CANCELLED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Cancelled",
                            SortOrder = 100,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000c"),
                            Code = "READY_FOR_PAYMENT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Ready for Payment",
                            SortOrder = 110,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000d"),
                            Code = "PAID",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Paid",
                            SortOrder = 120,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000e"),
                            Code = "ARCHIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Archived",
                            SortOrder = 130,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Code = "RECEIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Received",
                            SortOrder = 10,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Code = "EXTRACTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Extracted",
                            SortOrder = 15,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Code = "PROCESSING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Processing",
                            SortOrder = 20,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Code = "DUPLICATE_SUSPECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Duplicate Suspected",
                            SortOrder = 30,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Code = "AWAITING_REVIEW",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Review",
                            SortOrder = 40,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Code = "CHECKED_READY_TO_APPROVE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Checked & Ready to Approve",
                            SortOrder = 45,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Code = "NEEDS_REVIEW_FEBINA",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Needs Review by Febina",
                            SortOrder = 46,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Code = "NEEDS_QUERY",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Needs Query",
                            SortOrder = 50,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000009"),
                            Code = "QUERY_RAISED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Query Raised",
                            SortOrder = 60,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000a"),
                            Code = "AWAITING_SUPPLIER_RESPONSE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Supplier Response",
                            SortOrder = 70,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000b"),
                            Code = "APPROVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Approved",
                            SortOrder = 80,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000c"),
                            Code = "REJECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Rejected",
                            SortOrder = 90,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000d"),
                            Code = "CANCELLED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Cancelled",
                            SortOrder = 100,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000e"),
                            Code = "READY_FOR_PAYMENT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Ready for Payment",
                            SortOrder = 110,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000f"),
                            Code = "PAID",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Paid",
                            SortOrder = 120,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000010"),
                            Code = "ARCHIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Archived",
                            SortOrder = 130,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DomainName", "TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("WorkflowTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            DomainName = "Invoice",
                            IsDeleted = false,
                            Name = "Platform Default"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            DomainName = "Invoice",
                            IsDeleted = false,
                            Name = "GB Skips Invoice Workflow",
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "FromStatusCode", "ToStatusCode")
                        .IsUnique();

                    b.ToTable("WorkflowTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ce4259d-0754-6688-c193-7b0f39355737"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "RECEIVED",
                            IsDeleted = false,
                            ToStatusCode = "PROCESSING",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("bd66a1c6-5e50-c1e8-5503-364419ad922b"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "PROCESSING",
                            IsDeleted = false,
                            ToStatusCode = "EXTRACTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("c5ad3ccb-c890-3f5b-cd6d-b5214ed6806b"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "EXTRACTED",
                            IsDeleted = false,
                            ToStatusCode = "AWAITING_REVIEW",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("ad3f0932-9a7f-da45-76d4-b0e504b1ef9e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            ToStatusCode = "NEEDS_QUERY",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("9de6f32b-80ac-4eac-03bd-a055c0ae6ba4"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_QUERY",
                            IsDeleted = false,
                            ToStatusCode = "QUERY_RAISED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("ed2a8e1a-c07a-83bd-3fc9-08577e177bb6"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "QUERY_RAISED",
                            IsDeleted = false,
                            ToStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d3d1747c-2195-7b52-dfdf-a8efe59fabac"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            IsDeleted = false,
                            ToStatusCode = "AWAITING_REVIEW",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a52db712-cb7c-cb8e-2996-eaf31c552a81"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f54eb22e-3be5-1d58-aed5-d58425674d97"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "QUERY_RAISED",
                            IsDeleted = false,
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("7a82b7fa-4176-972c-7d28-c230f195eb39"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            IsDeleted = false,
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("655395ba-a8a4-803f-46d9-b39a332d4795"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "RECEIVED",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("9f7faa8d-f632-9818-7579-04343ab17db1"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "PROCESSING",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("5511c330-96de-3c94-6ef3-a908dc0b4c51"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "EXTRACTED",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("ed45b9a4-88f0-a507-5a14-d5991d8650c2"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("829fe0dc-78e6-a14b-98b2-7ac5e98e9815"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_QUERY",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d51c1405-9c22-32ba-0342-38212d2ba841"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "QUERY_RAISED",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("607e581d-99a1-047e-f71b-f0daed12c28e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            IsDeleted = false,
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3f4244f3-9cd6-920c-a649-cfe1b5c4a335"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "REJECTED",
                            IsDeleted = false,
                            ToStatusCode = "AWAITING_REVIEW",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("79252cb8-2a0f-13d7-e5ac-81c472d95548"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CANCELLED",
                            IsDeleted = false,
                            ToStatusCode = "RECEIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f3e1eac1-9a5d-8181-6ee3-e9416c36782a"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "APPROVED",
                            IsDeleted = false,
                            ToStatusCode = "READY_FOR_PAYMENT",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a19dd505-74e0-c453-5c41-74077fcfb544"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "READY_FOR_PAYMENT",
                            IsDeleted = false,
                            ToStatusCode = "PAID",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("5f68b404-babc-4199-172d-9c223e7f02f4"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "PAID",
                            IsDeleted = false,
                            ToStatusCode = "ARCHIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("de760142-342c-cc95-eeb8-f70e1a6e34de"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "REJECTED",
                            IsDeleted = false,
                            ToStatusCode = "ARCHIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("f1451bb6-00ec-32f7-97a5-a8b78a41f75d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CANCELLED",
                            IsDeleted = false,
                            ToStatusCode = "ARCHIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("803e1c56-8854-51ef-2bf1-f08206e22f9a"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            ToStatusCode = "APPROVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("ed304a4b-a5e7-4d51-0a2c-bb08bc5f66b7"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "RECEIVED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "PROCESSING",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c60db0b2-c8be-822d-0a0e-f316986b67c8"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "PROCESSING",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "EXTRACTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e827c842-823f-fcaf-6b58-82e5be2ca330"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "EXTRACTED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "AWAITING_REVIEW",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("1a3403f2-5bc1-996b-f048-4840d46f5000"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "NEEDS_QUERY",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("0d1d271f-6d15-a0fa-1357-466070d826ca"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_QUERY",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "QUERY_RAISED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("c2599b00-4f30-3fa0-791a-164a3696c10d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "QUERY_RAISED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("042ac4e7-fcda-cddb-552a-99bc87a71902"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "AWAITING_REVIEW",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a049a50b-a162-61b1-159a-53b893fe62c4"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("6e5951d2-5abf-a622-7da5-0b9fd25abaa2"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "QUERY_RAISED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("95d1b36b-aa59-c961-901d-eaadaa72a238"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("8da8abb5-0f89-ff8b-be65-de073832b7ae"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "RECEIVED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("d86a825f-602e-aabc-6c7b-ce21737da5dd"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "PROCESSING",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("1532ebbf-a773-fb1c-504e-817b000a9539"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "EXTRACTED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("ebfa2b8a-3f2c-7d93-279b-c00baeb46aac"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("bc4941c8-e905-609b-e885-f108c0e3458e"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_QUERY",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("46cf4fd5-1626-fa56-a496-311c135707db"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "QUERY_RAISED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("2ac61aee-4df1-1fdb-92cf-f2bc4ffe4733"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_SUPPLIER_RESPONSE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CANCELLED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("3fb94c0a-9718-a9ed-4e26-59419469bb52"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "REJECTED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "AWAITING_REVIEW",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("44f453de-efee-a70a-92f1-c2a3b230e086"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CANCELLED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "RECEIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("d642c5f1-0585-e62b-de0a-cc7ebeb434ad"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "APPROVED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "READY_FOR_PAYMENT",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("fbd5c2ce-2041-d03f-235c-55231486b1e9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "READY_FOR_PAYMENT",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "PAID",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("199a4579-f20e-4fbd-98e5-4512088d0b9d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "PAID",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "ARCHIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("bb685725-37d3-57f2-1386-98a008bfc684"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "REJECTED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "ARCHIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("aec013cd-abf8-f59c-be87-f2a491057379"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CANCELLED",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "ARCHIVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("9e7caae8-924a-4984-5586-3098236f53c3"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CHECKED_READY_TO_APPROVE",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("ab275607-0a90-c081-a018-5a7bee48f4da"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CHECKED_READY_TO_APPROVE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "APPROVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("3fb39133-3218-fa2c-31da-1ab9761650f5"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "AWAITING_REVIEW",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "NEEDS_REVIEW_FEBINA",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("3b2c910f-d7e5-c2aa-5bf7-147f17634ba0"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CHECKED_READY_TO_APPROVE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "NEEDS_REVIEW_FEBINA",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("cc00cbf0-6a62-a877-4d21-d1f9e812c4f5"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_REVIEW_FEBINA",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "CHECKED_READY_TO_APPROVE",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("dcba36e4-7a55-049a-a432-36c3aa776174"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_REVIEW_FEBINA",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "NEEDS_QUERY",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e25855ae-a0fc-1fa3-e76c-04034c18926d"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "NEEDS_REVIEW_FEBINA",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "REJECTED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("08e0db6e-4319-39c5-28bb-0ea9b75c5c50"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CHECKED_READY_TO_APPROVE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "NEEDS_QUERY",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.InvoiceNote", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Notes")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.StatusReference", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
