// <auto-generated />
using System;
using APFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723191924_AddSourceDocumentContentHash")]
    partial class AddSourceDocumentContentHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APFlow.Domain.Entities.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresDualControl")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Domain", "TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("ApprovalPolicies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            Domain = "InvoiceApproval",
                            IsDeleted = false,
                            RequiredRole = "FINANCE_MANAGER",
                            RequiresDualControl = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PreviousValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("DuplicateCheckReason")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal?>("GrossTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPotentialDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceDocumentBlobName")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("SourceDocumentContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceEmailMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierInvoiceNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Vat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TenantId", "InvoiceDate");

                    b.HasIndex("TenantId", "SourceDocumentContentHash");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "SupplierId");

                    b.ToTable("Invoices", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.InvoiceNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("TenantId", "InvoiceId");

                    b.ToTable("InvoiceNotes", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.StatusReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "Code")
                        .IsUnique();

                    b.ToTable("StatusReferences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "RECEIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Received",
                            SortOrder = 10,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Code = "EXTRACTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Extracted",
                            SortOrder = 15,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Code = "PROCESSING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Processing",
                            SortOrder = 20,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Code = "DUPLICATE_SUSPECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Duplicate Suspected",
                            SortOrder = 30,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Code = "AWAITING_REVIEW",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Review",
                            SortOrder = 40,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Code = "NEEDS_QUERY",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Needs Query",
                            SortOrder = 50,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Code = "QUERY_RAISED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Query Raised",
                            SortOrder = 60,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Code = "AWAITING_SUPPLIER_RESPONSE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Supplier Response",
                            SortOrder = 70,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Code = "APPROVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Approved",
                            SortOrder = 80,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000a"),
                            Code = "REJECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Rejected",
                            SortOrder = 90,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000b"),
                            Code = "CANCELLED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Cancelled",
                            SortOrder = 100,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000c"),
                            Code = "READY_FOR_PAYMENT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Ready for Payment",
                            SortOrder = 110,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000d"),
                            Code = "PAID",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Paid",
                            SortOrder = 120,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-00000000000e"),
                            Code = "ARCHIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Archived",
                            SortOrder = 130,
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Code = "RECEIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Received",
                            SortOrder = 10,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Code = "EXTRACTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Extracted",
                            SortOrder = 15,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Code = "PROCESSING",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Processing",
                            SortOrder = 20,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            Code = "DUPLICATE_SUSPECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Duplicate Suspected",
                            SortOrder = 30,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            Code = "AWAITING_REVIEW",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Review",
                            SortOrder = 40,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000006"),
                            Code = "CHECKED_READY_TO_APPROVE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Checked & Ready to Approve",
                            SortOrder = 45,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000007"),
                            Code = "NEEDS_REVIEW_FEBINA",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Needs Review by Febina",
                            SortOrder = 46,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000008"),
                            Code = "NEEDS_QUERY",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Needs Query",
                            SortOrder = 50,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000009"),
                            Code = "QUERY_RAISED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Query Raised",
                            SortOrder = 60,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000a"),
                            Code = "AWAITING_SUPPLIER_RESPONSE",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Awaiting Supplier Response",
                            SortOrder = 70,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000b"),
                            Code = "APPROVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Approved",
                            SortOrder = 80,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000c"),
                            Code = "REJECTED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Rejected",
                            SortOrder = 90,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000d"),
                            Code = "CANCELLED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Cancelled",
                            SortOrder = 100,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000e"),
                            Code = "READY_FOR_PAYMENT",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Ready for Payment",
                            SortOrder = 110,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-00000000000f"),
                            Code = "PAID",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = false,
                            Name = "Paid",
                            SortOrder = 120,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000010"),
                            Code = "ARCHIVED",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            IsDeleted = false,
                            IsTerminal = true,
                            Name = "Archived",
                            SortOrder = 130,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DomainName", "TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("WorkflowTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            DomainName = "Invoice",
                            IsDeleted = false,
                            Name = "Platform Default"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            DomainName = "Invoice",
                            IsDeleted = false,
                            Name = "GB Skips Invoice Workflow",
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatusCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("WorkflowTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTemplateId", "FromStatusCode", "ToStatusCode")
                        .IsUnique();

                    b.ToTable("WorkflowTransitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "system",
                            FromStatusCode = "CHECKED_READY_TO_APPROVE",
                            IsDeleted = false,
                            TenantId = new Guid("00000000-0000-0000-0000-0000000b5121"),
                            ToStatusCode = "APPROVED",
                            WorkflowTemplateId = new Guid("00000000-0000-0000-0001-000000000002")
                        });
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.InvoiceNote", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Notes")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.StatusReference", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Statuses")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTransition", b =>
                {
                    b.HasOne("APFlow.Domain.Entities.WorkflowTemplate", "WorkflowTemplate")
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkflowTemplate");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("APFlow.Domain.Entities.WorkflowTemplate", b =>
                {
                    b.Navigation("Statuses");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
